version: "3.8"
services:
  main:
    image: "trafex/php-nginx"
    restart: unless-stopped
    working_dir: "/var/www"
    ports:
      - "8000:8080"
    networks:
      - main_network
    volumes:
      - ".:/var/www"
      - "./config/nginx/conf.d:/etc/nginx/conf.d"
  mysql:
    image: mysql
    tty: true
    restart: unless-stopped
    ports:
      - "8888:3306"
    volumes:
      - "_database:/var/lib/mysql"
    environment:
      SERVICE_NAME: mysql
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ci4
    networks:
      - main_network
networks:
  main_network:
    driver: bridge
volumes:
  _database:
    driver: local